<?php
declare(strict_types=1);

/** @version 1.0.0 */

use LokiCheckout\PaypalExpress\Component\PaypalExpress\PaypalExpressViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\CssClass;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CssClass $css */
/** @var PaypalExpressViewModel $viewModel */
/** @var ViewModelFactory $viewModelFactory */
?>
<div class="<?= /* @noEscape */
$css('') ?>">
    <div x-ref="buttons"></div>

    <div
        data-pp-message
        data-pp-style-layout="text"
        data-pp-style-logo-type="inline"
        data-pp-style-text-color="black"
        data-pp-style-text-size="12"
        data-pp-amount="<?= $escaper->escapeHtml($viewModel->getAmount()) ?>"
        data-pp-placement="payment">
    </div>
</div>

