<?php
declare(strict_types=1);

/** @version 1.0.4 */

use LokiCheckout\PaypalExpress\ViewModel\PaypalSdk;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelFactory $viewModelFactory */
/** @var PaypalSdk $paypalSdk */

$paypalSdk = $viewModelFactory->create(PaypalSdk::class);
?>
<script src="<?= /* @noEscape */ $paypalSdk->getSdkUrl() ?>"></script>
